### ISSUE TITLE
Ignore certain container

### ISSUE THREAD

**Issue by jpdsceu** [dockupdater/dockupdater#23]
Hi there,

Is it possible to also ignore a certain container?
For example, I have a container which is used in Production and I need to make sure this one is not updated automatically.

I am unable to find this in the documentation.

Thanks.

**Comment by zaggash** [comment]
https://www.dockupdater.dev/Labels.html#disable-update

**Comment by jpdsceu** [comment]
I still haven't managed to disable a certain docker container (not using swarm)
This is an example of my dockupdater in docker-compose

```
    dockupdater:
        container_name: Dockupdater
        environment:
            - TZ=Europe/Amsterdam
            - CLEANUP=true
            - CRON=0 5 * * *
        volumes:
            - '/volume2/docker/docker.sock:/var/run/docker.sock:rw'
            - '/volume2/docker/Dockupdater/templates:/app/dockupdater/templates:rw'
        networks:
            private:
                ipv4_address: 10.2.0.5
        hostname: NAS
        restart: unless-stopped
        image: dockupdater/dockupdater
```

How can I ensure that for example Radarr isn't updated by dockupdater?

Thank you.
